"""The deviation report: facts rendered deterministically, narrative left to the agent.

The split matters and is deliberate. A deviation record is a regulated document and every
*number* in it has to be re-derivable from the incident record — so every number here is
filled from the verdict JSON by code, not by a model. What the model contributes is the
sections that genuinely need judgement and language: the investigation narrative, the root
cause assessment, the CAPA proposal.

That is why this module renders a report with explicit ``_TO BE COMPLETED BY_`` markers rather
than a finished document. A template that silently leaves a blank invites an agent to fill it
with something plausible; a template that names who owes what does not.

Aligned with WHO TRS-999 Annex 5 (excursion evaluation) and the general shape of a GDP
deviation record. It is not a regulatory form and does not claim to be one.
"""

from __future__ import annotations

from typing import Any

__all__ = ["deviation_report"]

#: Sections the deterministic layer must never write. Named in the output so a reviewer can
#: see at a glance what is machine fact and what is still a human's or the agent's to write.
_AGENT_SECTIONS = (
    "Investigation narrative",
    "Root cause assessment",
    "Corrective and preventive action (CAPA)",
)


def _fmt(value: Any, suffix: str = "", places: int = 2) -> str:
    if value is None:
        return "_not recorded_"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f"{value:.{places}f}{suffix}"
    return f"{value}{suffix}"


def deviation_report(
    verdict: dict[str, Any],
    shipment: dict[str, Any] | None = None,
    product: dict[str, Any] | None = None,
    consignees: list[dict[str, Any]] | None = None,
    incident_id: str = "",
    value_at_risk_usd: float | None = None,
) -> str:
    """Render the factual skeleton of a deviation report from a verdict JSON document.

    Args:
        verdict: the object emitted by ``python -m coldcall.cli`` — used verbatim. Nothing
            here recomputes or rounds a number the module already decided.
        shipment / product / consignees: context rows from the incident store.
        incident_id: the TrueForge session id, which is the incident record's identifier.
        value_at_risk_usd: units × unit value, if known.

    Returns:
        Markdown. Sections the agent must complete are marked, not left blank.
    """
    # Sections are numbered as they are emitted rather than hard-coded, because two of them
    # are conditional. Fixed numbers meant a report *without* route context jumped from 4 to
    # 6 — and in a regulated document a missing section number reads as a missing section,
    # which is exactly the wrong thing for an auditor to wonder about.
    _section_numbers = iter(range(1, 99))

    def head(title: str) -> str:
        return f"## {next(_section_numbers)}. {title}"

    shipment = shipment or {}
    product = product or {}
    consignees = consignees or []
    excursion = verdict.get("excursion", {})
    policy = verdict.get("policy", {})
    label = verdict.get("label", {})

    verdict_name = str(verdict.get("verdict", "unknown")).replace("_", " ").upper()

    lines: list[str] = [
        f"# Deviation record — temperature excursion, lot {shipment.get('lot_id', '?')}",
        "",
        f"**Incident:** `{incident_id or 'not recorded'}`  ",
        f"**Disposition:** **{verdict_name}**  ",
        "**Status:** draft — awaiting quality review and signature",
        "",
        "> Generated by ColdCall. Every figure below is computed by the deterministic"
        " disposition module and is re-derivable from the incident record. This is decision"
        " support; it is not a release decision.",
        "",
        head("Consignment"),
        "",
        "| | |",
        "|---|---|",
        f"| Shipment | `{shipment.get('id', '?')}` |",
        f"| Lot | `{shipment.get('lot_id', '?')}` |",
        f"| Product | {product.get('name', verdict.get('product', {}).get('brand_name', '?'))} |",
        f"| Units | {shipment.get('units', '?')} |",
        f"| Route | {shipment.get('origin', '?')} → {shipment.get('destination', '?')} |",
        f"| Carrier | {shipment.get('carrier', '?')} |",
    ]
    if value_at_risk_usd is not None:
        lines.append(f"| Value at risk | ${value_at_risk_usd:,.2f} |")

    lines += [
        "",
        head("Labelled storage conditions"),
        "",
        f"- Labelled range: **{_fmt(label.get('lower_c'), ' °C', 1)} to "
        f"{_fmt(label.get('upper_c'), ' °C', 1)}**",
    ]
    provenance = product.get("label_provenance") or verdict.get("product", {}).get(
        "storage_and_handling_verbatim"
    )
    if provenance:
        lines += ["", f"> {provenance}", ""]

    lines += [
        head("The excursion"),
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Total record | {_fmt(excursion.get('minutes_total'), ' min', 1)} |",
        f"| Time out of labelled range | "
        f"{_fmt(excursion.get('minutes_out_of_range'), ' min', 1)} |",
        f"| — above the maximum | {_fmt(excursion.get('minutes_above'), ' min', 1)} |",
        f"| — below the minimum | {_fmt(excursion.get('minutes_below'), ' min', 1)} |",
        f"| Peak temperature | {_fmt(excursion.get('max_c'), ' °C', 1)} |",
        f"| Minimum temperature | {_fmt(excursion.get('min_c'), ' °C', 1)} |",
        "",
        head("Stability evaluation"),
        "",
        "| Measure | Value | Basis |",
        "|---|---|---|",
        f"| Mean kinetic temperature | {_fmt(verdict.get('mkt_c'), ' °C')} | "
        f"USP <1079>, ΔH {_fmt(policy.get('activation_energy_j_per_mol'), ' J/mol', 0)} |",
        f"| Stability budget consumed | {_fmt(verdict.get('budget_consumed_pct'), '%', 1)} | "
        f"{_fmt(policy.get('allowed_excursion_hours'), ' h', 1)} allowance |",
        f"| Margin to next-worse verdict | {_fmt(verdict.get('margin_pct'), ' pp', 1)} | "
        f"policy thresholds {_fmt(policy.get('retest_at_pct'), '%', 0)} / "
        f"{_fmt(policy.get('destroy_at_pct'), '%', 0)} |",
        f"| Estimated potency remaining | {_fmt(verdict.get('est_potency_pct'), '%')} | "
        f"first-order Arrhenius **ESTIMATE, not an assay** |",
        "",
    ]

    if verdict.get("is_borderline"):
        lines += [
            "> **This call is borderline.** It sits within a few percentage points of a"
            " different disposition. The policy thresholds are ColdCall's, not the label's,"
            " so a quality system with different thresholds would reach a different answer on"
            " the same data. Reviewer attention is warranted.",
            "",
        ]

    route = verdict.get("route_context")
    if isinstance(route, dict) and not route.get("error"):
        attribution = str(route.get("attribution", "undetermined")).replace("_", " ")
        lines += [
            head("Route context — why the load warmed"),
            "",
            "The disposition arithmetic says what happens to the pallet. This says what to "
            "investigate, which is a different question with a different corrective action.",
            "",
            "| Measure | Value |",
            "|---|---|",
            f"| Attribution | **{attribution.upper()}** |",
            f"| Median load temperature above outside air | "
            f"{_fmt(route.get('median_gap_c'), ' °C', 1)} |",
            f"| Peak inside the consignment | {_fmt(route.get('peak_internal_c'), ' °C', 1)} |",
            f"| Peak outside air on the route | {_fmt(route.get('peak_ambient_c'), ' °C', 1)} |",
            f"| Excursion readings matched to weather | {route.get('matched_readings', '?')} of "
            f"{route.get('total_excursion_readings', '?')} |",
            "",
        ]
        evidence = route.get("location_evidence")
        if isinstance(evidence, dict):
            lines += [
                "",
                "**Where the consignment was, and how that is known**",
                "",
                "| | |",
                "|---|---|",
                f"| Coordinate | {evidence.get('latitude')}, {evidence.get('longitude')} |",
                f"| Provenance | **{evidence.get('provenance')}** |",
                f"| Fixes available | {evidence.get('fix_count')}, "
                f"{evidence.get('earliest_fix', 'n/a')} to {evidence.get('latest_fix', 'n/a')} |",
                f"| Spread of those fixes | {_fmt(evidence.get('fix_spread_m'), ' m', 0)} |",
                f"| Gap to the excursion window | "
                f"{_fmt(abs(evidence.get('gap_hours_to_window') or 0), ' h', 1)}, "
                f"{evidence.get('gap_direction')} |",
                "",
            ]
            if route.get("qualified"):
                reason = {
                    "provenance_unstated": (
                        "**nothing records when this position was taken**, so whether it "
                        "describes the consignment during the excursion is unknown"
                    ),
                    "recorded_after_window": (
                        "**every fix was recorded after the excursion closed** — it is where "
                        "the consignment ended up, not where it was while it warmed"
                    ),
                }.get(
                    str(route.get("location_confidence")),
                    "the consignment is **assumed** to have stayed in conditions comparable "
                    "to its last recorded position",
                )
                lines += [
                    f"> **This attribution is QUALIFIED.** The weather is real and the "
                    f"arithmetic is real, but *which* weather applies rests on an assumption: "
                    f"{reason}. That is an assumption, not an observation, and a reader acting "
                    f"on this section should weigh it as one.",
                    "",
                ]
        lines += [f"{i}. {note}" for i, note in enumerate(route.get("notes", []), 1)]
        if route.get("ambient_source"):
            lines += ["", f"> Weather provenance: {route['ambient_source']}"]
        lines += [
            "",
            f"> The {_fmt(route.get('containment_gap_threshold_c'), ' °C', 1)} gap threshold "
            f"separating a containment failure from environmental exposure is **ColdCall "
            f"policy, not a regulatory value.** A closed vehicle in sun runs warmer than the "
            f"shade temperature the archive reports, so some positive gap is expected.",
            "",
        ]
    elif isinstance(route, dict) and route.get("error"):
        lines += [
            head("Route context — why the load warmed"),
            "",
            f"_Not available: {route['error']}_ — the cause of the excursion is therefore "
            "**not established** in this record. Do not infer one from the temperature alone.",
            "",
        ]

    check = verdict.get("cross_check")
    if isinstance(check, dict):
        agreed = check.get("agrees")
        lines += [
            head("Independent verification"),
            "",
            "The disposition was computed **twice**, by deliberately different numerical "
            "routes, and the results were compared before this record was produced.",
            "",
            "| | |",
            "|---|---|",
            f"| Agreement | **{'YES' if agreed else 'NO — DO NOT ACT ON THIS RECORD'}** |",
            f"| Primary MKT | {_fmt(check.get('primary_mkt_c'), ' °C', 4)} |",
            f"| Independent MKT | {_fmt(check.get('independent_mkt_c'), ' °C', 4)} |",
            f"| Difference | {check.get('mkt_difference_c', '?')} °C |",
            f"| Independent verdict | "
            f"{str(check.get('independent_verdict', '?')).replace('_', ' ')} |",
            "",
            f"> Method: {check.get('method', '')}",
            "",
            f"> Limit: {check.get('limits', '')}",
            "",
        ]
        if not agreed:
            lines += ["**Disagreements:**", ""]
            lines += [f"- {d}" for d in check.get("disagreements", [])]
            lines.append("")

    lines += [head("Basis for the disposition"), ""]
    lines += [f"{i}. {reason}" for i, reason in enumerate(verdict.get("rationale", []), 1)]
    lines += [
        "",
        head("What is regulation and what is ColdCall policy"),
        "",
        "| Regulation-anchored | ColdCall policy |",
        "|---|---|",
        "| The MKT formula (USP <1079>, ICH Q1A) | The percent-of-budget thresholds above |",
        "| The labelled storage range, from the product's own openFDA label | The excursion"
        " allowance in hours |",
        "| Excursion evaluation per WHO TRS-999 Annex 5 | The potency estimate's parameters |",
        "",
        f"> {policy.get('source', 'ColdCall demo policy — not a regulatory limit')}",
        "",
        "Verified against openFDA: **no real drug label states a permitted excursion"
        " duration.** Labels pairing an excursion range with a number of hours describe"
        " post-reconstitution in-use stability, which is a different allowance.",
        "",
    ]

    if consignees:
        lines += [
            head("Affected consignees"),
            "",
            "| Consignee | Units expected |",
            "|---|---|",
        ]
        lines += [
            f"| {c.get('name', '?')} | {c.get('units_expected', '?')} |" for c in consignees
        ]
        lines.append("")

    lines += [head("Sections to be completed"), ""]
    for section in _AGENT_SECTIONS:
        lines += [
            f"### {section}",
            "",
            "_TO BE COMPLETED BY the Compliance Officer strand. Do not leave this blank and"
            " do not fill it with a restatement of the numbers above._",
            "",
        ]

    lines += [
        head("Signature"),
        "",
        "| | |",
        "|---|---|",
        "| Prepared by | ColdCall (automated) |",
        "| Reviewed by | _pending_ |",
        "| Disposition approved by | _pending — the release decision is the QA director's_ |",
        "",
        "---",
        "",
        "_Telemetry is real recorded shipment data, replayed. Not live telemetry."
        " See `replay/SHIPMENT.md` for provenance and selection criteria._",
    ]

    return "\n".join(lines) + "\n"
